# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171009_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
